name: Build and deploy

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          yarn

      - name: Build
        run: |
          yarn build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dest
          path: ./dest/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: dest
      
      - name: Initialise
        run: |
          git init
          git config user.name ${{github.actor}}
          git config user.email ${{github.actor}}@users.noreply.github.com
          
      - name: Commit
        run: |
          git add .
          git commit -m "${{github.event.head_commit.message}}"
          
      - name: Publish
        run: |
          git push -f https://${{ secrets.DEPLOY_TOKEN }}@github.com/${{ github.repository }}.git HEAD:gh-pages

