name: Github Pages Deploy

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Build
        run: |
          yarn build
        
      - name: copy
        run: |
          cp ./dest/ ../
          cd ../
          dir
          cd dest
          dir
