name: Github Pages Deploy

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          yarn install
  
      - name: Build Project
        run: |
          yarn build
        
      - name: Copy
        run: |
          cp ./dest/ ../ -r
      
      - name: Initialise
        run: |
          cd ../dest/
          git init
          git config user.name ${{GITHUB_ACTOR}}
          git config user.email ${{GITHUB_ACTOR}}@users.noreply.github.com
          
      - name: Commit
        run: |
          git add .
          git commit -m ${{github.event.head_commit.message}}
          
      - name: Publish
        run: |
          git push -f https://${{ secrets.DEPLOY_TOKEN }}@github.com/${{ GITHUB_REPOSITORY }}.git HEAD:gh-pages

